version: 2

models:
  - name: customer_analysis
    description: >
      Main customer analysis model that combines all staging components to provide
      comprehensive customer segmentation with recent order history. Replicates
      the complete business logic from the original BigQuery SQL.
    
    columns:
      - name: customer_id
        description: Unique identifier for the customer
        tests:
          - not_null
          - unique
      
      - name: total_spent
        description: Total amount spent by the customer across all orders
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: total_orders
        description: Total number of orders placed by the customer
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      
      - name: last_3_orders
        description: Array of the customer's last 3 orders with details
        tests:
          - not_null
      
      - name: customer_tier
        description: Customer segmentation tier (VIP, Preferred, Standard)
        tests:
          - not_null
          - accepted_values:
              values: ['VIP', 'Preferred', 'Standard']
      
      - name: analysis_date
        description: Date when the analysis was performed
        tests:
          - not_null
      
      - name: dbt_load_timestamp
        description: Timestamp when the record was loaded
        tests:
          - not_null
      
      - name: dbt_update_timestamp
        description: Timestamp when the record was last updated
        tests:
          - not_null