version: 2

models:
  - name: customer_analysis
    description: "Final customer analysis with spending totals, order history, and tier classification"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: total_spent
        description: "Total amount spent by the customer across all orders"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: total_orders
        description: "Total number of orders placed by the customer"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: total_items
        description: "Total number of items purchased by the customer"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: customer_tier
        description: "Customer tier classification (VIP, Preferred, Standard)"
        tests:
          - not_null
          - dbt_utils.accepted_values:
              values: ['VIP', 'Preferred', 'Standard']
      - name: last_3_orders
        description: "JSON array of the customer's last 3 orders"
        tests:
          - not_null
      - name: first_order_date
        description: "Date of the customer's first order"
        tests:
          - not_null
      - name: last_order_date
        description: "Date of the customer's most recent order"
        tests:
          - not_null
      - name: analysis_timestamp
        description: "Timestamp when the analysis was performed"
        tests:
          - not_null
      - name: etl_batch_id
        description: "ETL batch identifier for tracking"
        tests:
          - not_null

    tests:
      - dbt_utils.expression_is_true:
          expression: "first_order_date <= last_order_date"
          config:
            severity: error
      - dbt_utils.expression_is_true:
          expression: "total_spent = total_orders * avg_item_value * (total_items / total_orders)"
          config:
            severity: warn