name: 'sample_bigquery_1'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'sample_bigquery_1'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  sample_bigquery_1:
    # Configuration for all models in this project
    +materialized: table
    
    staging:
      # Configuration for staging models - raw data transformation
      +materialized: view
      +schema: staging_layer
    
    intermediate:
      # Configuration for intermediate models - business logic processing
      +materialized: ephemeral
    
    marts:
      # Configuration for mart models - final analytics output
      +materialized: table
      +schema: analytics_layer

# Global variables that can be referenced in models
vars:
  # Default values for common fields
  current_timestamp_format: 'yyyy-MM-dd HH:mm:ss'
  date_format: 'yyyy-MM-dd'
  etl_batch_id: "{{ run_started_at.strftime('%Y%m%d%H%M%S') }}"
  
  # Business logic thresholds
  vip_threshold: 10000
  preferred_threshold: 5000
  max_recent_orders: 3

# Test configurations
tests:
  +store_failures: true
  +schema_tests: true

# Package dependencies
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1