ukrg_vpaynet_consumption_load:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: consumption_layer
      threads: 4
      keepalives_idle: 240
      search_path: "{{ env_var('SNOWFLAKE_DATABASE') }}.consumption_layer"
      query_tag: "dbt_ukrg_vpaynet_consumption_load"
      
    staging:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: consumption_layer
      threads: 8
      keepalives_idle: 240
      search_path: "{{ env_var('SNOWFLAKE_DATABASE') }}.consumption_layer"
      query_tag: "dbt_ukrg_vpaynet_consumption_load_staging"
      
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: consumption_layer
      threads: 16
      keepalives_idle: 240
      search_path: "{{ env_var('SNOWFLAKE_DATABASE') }}.consumption_layer"
      query_tag: "dbt_ukrg_vpaynet_consumption_load_production"