name: 'gsapeu_tds_batch'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'gsapeu_tds_batch'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  gsapeu_tds_batch:
    # Configuration for all models in this project
    +materialized: table
    
    staging:
      # Configuration for staging models - represents trusted layer
      +materialized: view
      +schema: trusted_layer
    
    marts:
      # Configuration for mart models - represents transformed layer
      +materialized: table
      +schema: transformed_layer
      +pre-hook: "TRUNCATE TABLE {{ this }}"

# Global variables that can be referenced in models
vars:
  # Default values for common fields
  current_timestamp_format: 'yyyy-MM-dd HH:mm:ss'
  date_format: 'yyyy-MM-dd'
  etl_batch_id: "{{ run_started_at.strftime('%Y%m%d%H%M%S') }}"
  
  # Table configuration based on mapping document
  trusted_table_name: 'first_table'
  transformed_table_name: 'second_table'
  
  # Partitioning and clustering configuration
  partition_by: 'etl_batch_date'
  clustering_by: ['cust_nbr', 'batch_nbr', 'status']

# Test configurations
tests:
  +store_failures: true
  +schema_tests: true