gcp_dataflow_dbt:
  target: dev
  outputs:
    
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') | default('TRANSFORMER', true) }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') | default('ANALYTICS', true) }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') | default('TRANSFORMING', true) }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') | default('dbt_dev', true) }}"
      threads: 4
      keepalives_idle: 240
      search_path: "{{ env_var('SNOWFLAKE_SEARCH_PATH') | default('ANALYTICS', true) }}"
    
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') | default('TRANSFORMER', true) }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') | default('ANALYTICS', true) }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') | default('TRANSFORMING', true) }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') | default('dbt_prod', true) }}"
      threads: 8
      keepalives_idle: 240
      search_path: "{{ env_var('SNOWFLAKE_SEARCH_PATH') | default('ANALYTICS', true) }}"