name: 'ukrg_crossborder_itemized'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ukrg_crossborder_itemized'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  ukrg_crossborder_itemized:
    # Configuration for all models in this project
    +materialized: table
    
    staging:
      # Configuration for staging models - represents source data abstraction
      +materialized: view
      +schema: staging_layer
    
    marts:
      # Configuration for mart models - represents final output
      +materialized: incremental
      +schema: transformed_layer_commplat
      +unique_key: ['trans_sk_guid', 'type', 'sub_type', 'fee_type', 'status', 'exception_action_report_sk']
      +merge_update_columns: ['etlbatchid', 'update_date_time', 'trans_sk_guid', 'chargeback_sk_chargeback_eod', 'member_balancing_sk', 'mybank_vp_mp_reclass_items_sk', 'exception_action_report_sk', 'type', 'sub_type', 'fee_type', 'geographical_region', 'mybank_acquirer_id', 'hierarchy', 'merchant_number', 'merchant_number_int', 'acquirer_bin', 'order_id', 'alpha_currency_code', 'currency_exponent', 'amount', 'country_code', 'reference_transaction_id', 'status', 'reason_text', 'payment_method', 'processing_date', 'file_date', 'merchant_aggregate_reference', 'bin_aggregate_reference', 'arn', 'settlement_alpha_currency_code', 'expected_settled_amount', 'settlement_currency_exponent', 'expected_settlement_date', 'scheme_rate', 'card_type', 'card_type_desc', 'charge_type', 'charge_type_desc', 'domestic_international_ind', 'interchange_fee_program', 'interchange_fee_program_desc', 'interchange_rate', 'vp_mp_rejects_sk', 'system_trace_audit_number', 'retrieval_ref_number', 'card_country_code', 'account_funding_source', 'card_bin', 'bin_detail_sk']

# Global variables that can be referenced in models
vars:
  # Default values for common fields
  current_timestamp_format: 'yyyy-MM-dd HH:mm:ss'
  date_format: 'yyyy-MM-dd'
  etl_batch_id: "{{ run_started_at.strftime('%Y%m%d%H%M%S') }}"
  
  # Configuration specific to crossborder itemized processing
  mybank_corporate: '014'
  mybank_acquirer_id: 'COMPANYNAME'
  
  # Default values for static columns
  default_sk_value: '-1'
  fee_type: 'FEE'
  sub_type: 'TRANSACTION_FEE'
  fee_type_crossborder: 'CROSSBORDER_FEE'

# Test configurations
tests:
  +store_failures: true
  +schema_tests: true