version: 2

sources:
  - name: raw_data
    description: "Source data for sales analytics processing"
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: raw_layer
    tables:
      - name: orders
        description: "Raw orders data from BigQuery project.dataset.orders"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Unique identifier for customer"
            tests:
              - not_null
          - name: order_date
            description: "Date when order was placed"
            tests:
              - not_null
          - name: product_id
            description: "Unique identifier for product"
            tests:
              - not_null
          - name: quantity
            description: "Quantity of product ordered"
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: ">= 0"
          - name: price
            description: "Price per unit of product"
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: "> 0"