name: 'ukrg_lcot_uid_auth_dif'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ukrg_lcot_uid_auth_dif'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  ukrg_lcot_uid_auth_dif:
    # Configuration for all models in this project
    +materialized: table
    
    staging:
      # Configuration for staging models - represents source data abstraction
      +materialized: view
      +schema: backup_xl_layer
    
    marts:
      # Configuration for mart models - represents final output
      +materialized: incremental
      +schema: backup_xl_layer
      +unique_key: ['lcot_guid_key_sk']
      +merge_update_columns: ['etlbatchid_auth', 'etlbatchid_tran', 'joinind_auth_dif', 'joininddate_auth_dif', 'global_trid_source_dif', 'global_trid_source_tds', 'global_trid_dif', 'global_trid_tds', 'customer_unique_reference_number']

# Global variables that can be referenced in models
vars:
  # Default values for common fields
  current_timestamp_format: 'yyyy-MM-dd HH:mm:ss'
  date_format: 'yyyy-MM-dd'
  etl_batch_id: "{{ run_started_at.strftime('%Y%m%d%H%M%S%f')[:-3] }}"
  
  # Configuration specific to LCOT UID auth diff processing
  filter_date_interval_dif: 10
  filter_date_interval_auth_150: 150
  filter_date_interval_auth_5: 5
  filter_date_interval_180: 180
  filter_date_interval_365: 365
  filter_date_interval_20: 20
  filter_date_interval_current: 20
  
  # Default values for static columns
  default_sk_value: '-1'
  default_joinind_date: '20241020'

# Test configurations
tests:
  +store_failures: true
  +schema_tests: true