version: 2

seeds:
  - name: sample_orders_data
    description: "Sample orders data for testing customer sales analysis pipeline"
    config:
      alias: orders
      schema: raw_data
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: order_date
        description: "Date when order was placed"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
        tests:
          - not_null
      - name: quantity
        description: "Quantity of product ordered"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      - name: price
        description: "Price per unit of product"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false