version: 2

seeds:
  - name: sample_orders_data
    description: Sample orders data for testing and development
    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - not_null
      - name: customer_id
        description: Customer identifier
        tests:
          - not_null
      - name: order_date
        description: Date when the order was placed
        tests:
          - not_null
      - name: product_id
        description: Product identifier within the order
        tests:
          - not_null
      - name: quantity
        description: Quantity of the product ordered
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: price
        description: Price per unit of the product
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0