version: 2

seeds:
  - name: sample_orders_data
    description: >
      Sample orders data for testing and development. This seed provides
      representative data that covers various customer tiers and scenarios.
    
    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - not_null
      
      - name: customer_id
        description: Unique identifier for the customer
        tests:
          - not_null
      
      - name: order_date
        description: Date when the order was placed
        tests:
          - not_null
      
      - name: product_id
        description: Unique identifier for the product
        tests:
          - not_null
      
      - name: quantity
        description: Quantity of product ordered
        tests:
          - not_null
      
      - name: price
        description: Price of the product
        tests:
          - not_null