version: 2

seeds:
  - name: sample_orders_data
    description: "Sample orders data for development and testing purposes"
    config:
      column_types:
        order_id: varchar(50)
        customer_id: varchar(50)
        order_date: date
        product_id: varchar(50)
        quantity: integer
        price: decimal(10,2)
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
      
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
      
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - not_null
      
      - name: quantity
        description: "Quantity of product ordered"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      
      - name: price
        description: "Unit price of the product"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false