version: 2

seeds:
  - name: sample_orders
    description: "Sample orders data for testing customer analysis transformations"
    config:
      column_types:
        order_id: varchar
        customer_id: varchar
        order_date: date
        product_id: varchar
        quantity: number
        price: number(10,2)
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - not_null
      - name: quantity
        description: "Quantity of products ordered"
        tests:
          - not_null
          - expression_is_true:
              expression: "> 0"
      - name: price
        description: "Price per unit of the product"
        tests:
          - not_null
          - expression_is_true:
              expression: "> 0"