version: 2

seeds:
  - name: sample_orders_data
    description: "Sample orders data for development and testing purposes"
    config:
      schema: source_data
      alias: orders
    columns:
      - name: order_id
        description: "Unique identifier for orders"
        tests:
          - not_null
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
        tests:
          - not_null
      - name: quantity
        description: "Quantity of products ordered"
        tests:
          - not_null
      - name: price
        description: "Price per unit of product"
        tests:
          - not_null