version: 2

models:
  - name: customer_analysis
    description: "Final customer analysis with spending patterns, order history, and tier classification"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique
      
      - name: total_spent
        description: "Total amount spent by customer across all orders"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      
      - name: total_orders
        description: "Total number of orders placed by customer"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              inclusive: true
      
      - name: total_items_purchased
        description: "Total number of items purchased by customer"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              inclusive: true
      
      - name: avg_item_value
        description: "Average value per item purchased"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      
      - name: customer_tier
        description: "Customer tier based on total spending (VIP, Preferred, Standard)"
        tests:
          - not_null
          - accepted_values:
              values: ['VIP', 'Preferred', 'Standard']
      
      - name: avg_order_value
        description: "Average value per order"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      
      - name: customer_tenure_days
        description: "Number of days between first and last order"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      
      - name: etl_processed_timestamp
        description: "Timestamp when the record was processed in analytics layer"
        tests:
          - not_null