name: 'sample_bigquery'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'sample_bigquery'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  sample_bigquery:
    # Configuration for all models in this project
    +materialized: table
    
    staging:
      # Configuration for staging models - intermediate transformations
      +materialized: view
      +schema: staging_layer
    
    marts:
      # Configuration for mart models - final business output
      +materialized: table
      +schema: analytics_layer
      +pre-hook: "TRUNCATE TABLE {{ this }}"

# Global variables that can be referenced in models
vars:
  # Default values for common fields
  current_timestamp_format: 'yyyy-MM-dd HH:mm:ss'
  date_format: 'yyyy-MM-dd'
  
  # Customer tier thresholds
  vip_threshold: 10000
  preferred_threshold: 5000
  
  # Analytics configuration
  max_recent_orders: 3

# Test configurations
tests:
  +store_failures: true
  +schema_tests: true