version: 2

sources:
  - name: sales_data
    description: "Source data for sales analysis - migrated from BigQuery project.dataset.orders"
    tables:
      - name: orders
        description: "Orders table containing transaction details with product items"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Unique identifier for customers"
            tests:
              - not_null
          - name: order_date
            description: "Date when the order was placed"
            tests:
              - not_null
          - name: product_id
            description: "Unique identifier for products"
            tests:
              - not_null
          - name: quantity
            description: "Quantity of product ordered"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: price
            description: "Price per unit of the product"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0