version: 2

models:
  - name: stg_orders
    description: Staging model for orders data with data validation and preparation
    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Customer identifier
        tests:
          - not_null
      - name: order_date
        description: Date when the order was placed
        tests:
          - not_null
      - name: product_id
        description: Product identifier within the order
        tests:
          - not_null
      - name: quantity
        description: Quantity of the product ordered (safely cast to integer)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: price
        description: Price per unit of the product (safely cast to numeric)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: dbt_load_timestamp
        description: Timestamp when the record was first loaded by DBT
        tests:
          - not_null
      - name: dbt_update_timestamp
        description: Timestamp when the record was last updated by DBT
        tests:
          - not_null