version: 2

models:
  - name: stg_orders
    description: "Staging model for raw orders data with basic quality filters applied"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
        tests:
          - not_null
      - name: quantity
        description: "Quantity of products ordered"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: price
        description: "Price per unit of the product"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: line_total
        description: "Total value for this order line (quantity * price)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: loaded_at
        description: "Timestamp when the record was loaded"
        tests:
          - not_null