version: 2

sources:
  - name: source_data
    description: "Source data layer containing original orders data"
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: source_layer
    tables:
      - name: orders
        description: "Orders table containing transaction data with product details"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Customer identifier"
            tests:
              - not_null
          - name: order_date
            description: "Date when order was placed"
            tests:
              - not_null
          - name: product_id
            description: "Product identifier"
            tests:
              - not_null
          - name: quantity
            description: "Product quantity ordered"
            tests:
              - not_null
          - name: price
            description: "Product unit price"
            tests:
              - not_null