version: 2

seeds:
  - name: sample_orders_data
    description: "Sample order data for testing customer sales analysis"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: order_date
        description: "Date when order was placed"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
        tests:
          - not_null
      - name: quantity
        description: "Quantity ordered"
        tests:
          - not_null
      - name: price
        description: "Price per unit"
        tests:
          - not_null