version: 2

sources:
  - name: raw_sales
    description: "Source sales data from BigQuery project.dataset.orders"
    tables:
      - name: orders
        description: "Raw orders table with product line items"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
            tests:
              - not_null
          - name: customer_id
            description: "Unique identifier for each customer"
            tests:
              - not_null
          - name: order_date
            description: "Date when the order was placed"
            tests:
              - not_null
          - name: product_id
            description: "Unique identifier for each product"
            tests:
              - not_null
          - name: quantity
            description: "Quantity of product ordered"
            tests:
              - not_null
          - name: price
            description: "Price per unit of product"
            tests:
              - not_null