version: 2

models:
  - name: stg_orders
    description: "Staging model for orders data with basic data quality filters applied"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
          - unique
      
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
      
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - not_null
      
      - name: quantity
        description: "Quantity of product ordered"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      
      - name: price
        description: "Unit price of the product"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      
      - name: order_item_total
        description: "Total value for this order item (quantity * price)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      
      - name: etl_load_timestamp
        description: "Timestamp when the record was loaded into staging"
        tests:
          - not_null