version: 2

models:
  - name: stg_orders
    description: "Staging model for cleaned orders data"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
        tests:
          - not_null
      - name: quantity
        description: "Quantity of products ordered"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: price
        description: "Unit price of the product"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: line_total
        description: "Total value of the line item (quantity * price)"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"