version: 2

sources:
  - name: raw_data
    description: "Source data for customer sales analysis"
    tables:
      - name: orders
        description: "Raw orders table with transaction details"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Customer identifier"
            tests:
              - not_null
          - name: order_date
            description: "Date when the order was placed"
            tests:
              - not_null
          - name: product_id
            description: "Product identifier"
            tests:
              - not_null
          - name: quantity
            description: "Quantity of products ordered"
            tests:
              - not_null
          - name: price
            description: "Unit price of the product"
            tests:
              - not_null