version: 2

sources:
  - name: source_data
    description: "Source data from BigQuery equivalent tables"
    tables:
      - name: orders
        description: "Orders table containing order details with items"
        columns:
          - name: order_id
            description: "Unique identifier for orders"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Customer identifier"
            tests:
              - not_null
          - name: order_date
            description: "Date when the order was placed"
            tests:
              - not_null
          - name: product_id
            description: "Product identifier"
            tests:
              - not_null
          - name: quantity
            description: "Quantity of products ordered"
            tests:
              - not_null
          - name: price
            description: "Price per unit of product"
            tests:
              - not_null