version: 2

sources:
  - name: sales_data
    description: "Source sales data from Snowflake"
    database: "{{ var('source_database') }}"
    schema: "{{ var('source_schema') }}"
    tables:
      - name: orders
        description: "Raw orders table with order details and line items"
        columns:
          - name: order_id
            description: "Unique order identifier"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Customer identifier"
            tests:
              - not_null
          - name: order_date
            description: "Date when order was placed"
            tests:
              - not_null
          - name: product_id
            description: "Product identifier"
            tests:
              - not_null
          - name: quantity
            description: "Quantity ordered"
            tests:
              - not_null
          - name: price
            description: "Unit price of the product"
            tests:
              - not_null