version: 2

sources:
  - name: source_database
    description: "Source database containing order data"
    database: "{{ env_var('SOURCE_DATABASE', 'SOURCE_DB') }}"
    schema: "{{ env_var('SOURCE_SCHEMA', 'DATASET') }}"
    tables:
      - name: orders
        description: "Orders table containing order details with items"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
            tests:
              - not_null
          - name: customer_id
            description: "Customer identifier"
            tests:
              - not_null
          - name: order_date
            description: "Date when the order was placed"
            tests:
              - not_null
          - name: product_id
            description: "Product identifier"
            tests:
              - not_null
          - name: quantity
            description: "Quantity of product ordered"
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: ">= 0"
          - name: price
            description: "Unit price of the product"
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: ">= 0"