version: 2

models:
  - name: stg_orders
    description: "Staging model for raw orders data with basic quality filters"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      - name: quantity
        description: "Quantity of items ordered"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: price
        description: "Price per item"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: customer_analytics
    description: "Final customer analytics with order history and tier classification"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null
      - name: total_spent
        description: "Total amount spent by customer"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: total_orders
        description: "Total number of orders by customer"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: customer_tier
        description: "Customer tier classification"
        tests:
          - not_null
          - accepted_values:
              values: ['VIP', 'Preferred', 'Standard']