version: 2

sources:
  - name: trusted_layer
    description: "Source tables from the trusted data layer"
    database: SAMPLE_WAREHOUSE
    schema: TRUSTED_LAYER
    tables:
      - name: orders
        description: "Raw order data with product line items"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Unique identifier for the customer"
            tests:
              - not_null
          - name: order_date
            description: "Date when the order was placed"
            tests:
              - not_null
          - name: product_id
            description: "Unique identifier for the product"
            tests:
              - not_null
          - name: quantity
            description: "Quantity of the product ordered"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 1
          - name: price
            description: "Price per unit of the product"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0